CREATE TABLE USUARIO (
  ID int(11) NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(100) NOT NULL,
  USUARIO VARCHAR(100) NOT NULL,
  SENHA VARCHAR(100) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE CLIENTE (
  ID int(11) NOT NULL AUTO_INCREMENT,
  IDVERSAO int(11) NOT NULL,
  NOME VARCHAR(100) NOT NULL,
  CODIGOINTERNO VARCHAR(20),
  QUANTINSTALACOES int(11),
  QUANTDIAS int(11) NOT NULL,
  CNPJ VARCHAR(18) NOT NULL,
  BLOQUEADO int(11) NOT NULL,
  OBS VARCHAR(1000),
  QUANTMINSINC int(11) NOT NULL,
  PRIMARY KEY(ID)
);